version: '3'

services:

  nginx:
    image: nginx:1.13
    ports:
      - 80:80
    restart: always
    volumes:
      - ./devops/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./static:/static
    depends_on:
      - web

  web:
    image: registry.gitlab.com/your_name/django_docker_template:latest
    build:
      context: .
    container_name: web
    environment: 
      - ENGINE=django.db.backends.postgresql_psycopg2
      - POSTGRES_DB=postgres
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - DJANGO_SETTINGS_MODULE=django_docker_template.settings
    #When Direct Access on 8000
    #ports:
    #  - '8000:8000'
    command: bash -c 'python manage.py migrate --noinput && python manage.py collectstatic --noinput && gunicorn django_docker_template.wsgi:application -w 2 -b :8000 --capture-output --log-level=info'
    depends_on:
      - postgres
    volumes:
      - ./static:/static
    links:
      - postgres

  postgres:
    restart: always
    image: postgres:10
    container_name: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
